language: php
php:
- 7.0
- 7.1
- 7.2
install:
- composer install
after_script:
- vendor/bin/test-reporter --coverage-report=tests/log/coverage.xml
notifications:
  slack:
    rooms:
      secure: Cukg4H97nS5vpE2ziiBJGCOp/5cNLK2+Bj1OnpqsLbPzL+fTNnODvt9KAv88c5q+xQ+LtPLlGlu+S3lhHCUAPFOgdQkz/+QzYJUdZ7bt+CoW8Mh5eIsGAsQtp26UytIFnOOXKTbM1pYiP9rMcwpkjeE7lflA+wTyd4+DyaFmH9/AjvmtfM/cgl+ZBa+IfQWaShBHaQXhmV7lAb3yFeYrlBI61wfL2qTbzJlcCaMhLCR342uu1TwY2FcjgiogvyjgW6RmF7T51o/zxHWKCeHLKLTuyGJeIEA3EXDnIRWU1nLVRN11Fz66Gb+8nX2wUYzfSXm9Ca7K8u08g9+s6cSPScoJpU05ym5pzx6CONF1Or1umv23Ij7aGgF0lafkcytml1xIekfBM+pavjXZKJhmT9AoAGhuTMvUGGuN1Hn2VrpcNA8a03q/psi134aiNNrl2Y9jfj1J9Srsr3ebeQ8VvkQ0I4EBqYz6IHcq8WW0XOB3RA325MlHJSPDhRP1rnTYGJhL9kEi0dvjTlVFludnjJl3x5fbRJmcrBKpUCYNsXhwpdm1jDfdV1IVNKe3p1+uSViG6IDL0fqexQ8x2CX1TmVlodbVa26teSDGDVP5+FSmSN8e5DZC5zIAxhALOaIzkvgCTdmjJChW4S+gI/ijvOmmP0JTwk7a47hd9MKSjRU=
    on_success: change
    on_failure: always
    on_pull_requests: false
