version: '3.3'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: lightster/named-sprintf
    volumes:
      - .:/named-sprintf:cached
      - ~/.composer/:/root/.composer
